# Generated by Django 2.2.12 on 2021-06-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210618_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
